//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntPanelApplication.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AntPanelApplication")]
        public string Name {
            get {
                return ((string)(this["Name"]));
            }
            set {
                this["Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Meiryo UI, 12pt")]
        public global::System.Drawing.Font DefaultFont {
            get {
                return ((global::System.Drawing.Font)(this["DefaultFont"]));
            }
            set {
                this["DefaultFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RichTextEditor")]
        public string DefaultEditor {
            get {
                return ((string)(this["DefaultEditor"]));
            }
            set {
                this["DefaultEditor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BrowserEx")]
        public string DefaultBrowser {
            get {
                return ((string)(this["DefaultBrowser"]));
            }
            set {
                this["DefaultBrowser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("42")]
        public int DefaultBottomPanelHeight {
            get {
                return ((int)(this["DefaultBottomPanelHeight"]));
            }
            set {
                this["DefaultBottomPanelHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("56")]
        public int DefaultRightPanelWidth {
            get {
                return ((int)(this["DefaultRightPanelWidth"]));
            }
            set {
                this["DefaultRightPanelWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200, 800")]
        public global::System.Drawing.Size WindowSize {
            get {
                return ((global::System.Drawing.Size)(this["WindowSize"]));
            }
            set {
                this["WindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\sakura\\sakura.exe")]
        public string win_SakuraPath {
            get {
                return ((string)(this["win_SakuraPath"]));
            }
            set {
                this["win_SakuraPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\NextFTP\\NEXTFTP.EXE")]
        public string win_NextFTPPath {
            get {
                return ((string)(this["win_NextFTPPath"]));
            }
            set {
                this["win_NextFTPPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>F:\My Music\２つのミサ曲\２つのミサ曲.asx</string>
  <string>C:\home\KingFM.asx</string>
  <string>F:\My Video\flv\misaki.flv</string>
  <string>F:\My Music\KingFM\070104\MARTIN-Mass.wax</string>
  <string>F:\home\xjpeg\ePXXXFd.wmv</string>
  <string>http://v6.player.abacast.net/3</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BookMarks {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BookMarks"]));
            }
            set {
                this["BookMarks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>F:\My Music\KingFM\061122\MOZART-Horn_Concerto_No.2_in_E-flat_K.417.wax</string>
  <string>F:\My Music\２つのミサ曲\２つのミサ曲.asx</string>
  <string>C:\home\KingFM.asx</string>
  <string>F:\My Video\flv\misaki.flv</string>
  <string>F:\My Music\KingFM\070104\MARTIN-Mass.wax</string>
  <string>F:\My Music\KingFM\060804\MOZART-Piano_Concerto_No.13_in_C_K.415_387b.wax</string>
  <string>F:\My Music\KingFM\061030\MOZART-Piano_Concerto_No.12_in_A_K.414.wax</string>
  <string>F:\My Music\KingFM\060805\IBERT-Escales(Ports_of_Call).wax</string>
  <string>F:/My Music/KingFM/070108/MOZART-Piano_Concerto_No.1_in_F,_K.37.wax</string>
  <string>F:\home\xjpeg\ePXXXFd.wmv</string>
  <string>F:\My Music\KingFM\070107\IRELAND-Orchestral_Poem_in_A_minor.wax</string>
  <string>F:\My Music\KingFM\070112\KETCLBY-Bells_Across_the_Meadow.wax</string>
  <string>F:\My Music\KingFM\070115\HEINICHEN-Chamber_Sonata_in_A,_S.208.wax</string>
  <string>F:\My Music\KingFM\060810\GEMINIANI-Concerto_Grosso_in_B-flat_Op.5_2.wax</string>
  <string>F:\My Music\KingFM\070117\FALLA-Love,_the_Magician-Ritual_Fire_Dance.wax</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PreviousDocuments {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PreviousDocuments"]));
            }
            set {
                this["PreviousDocuments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection PreviousProjects {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PreviousProjects"]));
            }
            set {
                this["PreviousProjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost")]
        public string ServerRoot {
            get {
                return ((string)(this["ServerRoot"]));
            }
            set {
                this["ServerRoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Apache2.2\\htdocs")]
        public string win_DocumentRoot {
            get {
                return ((string)(this["win_DocumentRoot"]));
            }
            set {
                this["win_DocumentRoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\PSPad editor\\PSPad.exe")]
        public string win_PspadPath {
            get {
                return ((string)(this["win_PspadPath"]));
            }
            set {
                this["win_PspadPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\IDE\\devenv." +
            "exe")]
        public string Devenv17Path {
            get {
                return ((string)(this["Devenv17Path"]));
            }
            set {
                this["Devenv17Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Windows Media Player\\wmplayer.exe")]
        public string MediaPlayerPath {
            get {
                return ((string)(this["MediaPlayerPath"]));
            }
            set {
                this["MediaPlayerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\VideoLAN\\VLC\\vlc.exe")]
        public string win_VlcPath {
            get {
                return ((string)(this["win_VlcPath"]));
            }
            set {
                this["win_VlcPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\ant\\apache-ant-1.10.1\\bin\\ant.bat")]
        public string AntExecutablePath {
            get {
                return ((string)(this["AntExecutablePath"]));
            }
            set {
                this["AntExecutablePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\gradle-3.5\\bin\\gradle.bat")]
        public string GradlePath {
            get {
                return ((string)(this["GradlePath"]));
            }
            set {
                this["GradlePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe")]
        public string ChromePath {
            get {
                return ((string)(this["ChromePath"]));
            }
            set {
                this["ChromePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\ant\\apache-ant-1.10.1")]
        public string AntPath {
            get {
                return ((string)(this["AntPath"]));
            }
            set {
                this["AntPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("antPluginData.txt")]
        public string StorageFileName {
            get {
                return ((string)(this["StorageFileName"]));
            }
            set {
                this["StorageFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Git\\git-bash.exe")]
        public string GitPath {
            get {
                return ((string)(this["GitPath"]));
            }
            set {
                this["GitPath"] = value;
            }
        }
    }
}
